/*-------------------------------------------------------------------------
 *
 * catcoretable.c
 *	  Auto-generated C file from the catalog headers. Don't edit manually.
 *
 * WARNING: DO NOT MODIFY THIS FILE:
 * Generated by ./catcoregen.pl
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"
#include "catalog/catcore.h"
#include "catalog/catalog.h"
#include "catalog/gp_configuration.h"
#include "catalog/gp_fastsequence.h"
#include "catalog/gp_id.h"
#include "catalog/gp_policy.h"
#include "catalog/gp_san_config.h"
#include "catalog/gp_segment_config.h"
#include "catalog/gp_verification_history.h"
#include "catalog/gp_version.h"
#include "catalog/indexing.h"
#include "catalog/pg_aggregate.h"
#include "catalog/pg_amop.h"
#include "catalog/pg_amproc.h"
#include "catalog/pg_appendonly.h"
#include "catalog/pg_appendonly_alter_column.h"
#include "catalog/pg_attrdef.h"
#include "catalog/pg_auth_members.h"
#include "catalog/pg_authid.h"
#include "catalog/pg_autovacuum.h"
#include "catalog/pg_cast.h"
#include "catalog/pg_class.h"
#include "catalog/pg_constraint.h"
#include "catalog/pg_conversion.h"
#include "catalog/pg_database.h"
#include "catalog/pg_depend.h"
#include "catalog/pg_description.h"
#include "catalog/pg_extprotocol.h"
#include "catalog/pg_exttable.h"
#include "catalog/pg_filespace.h"
#include "catalog/pg_filespace_entry.h"
#include "catalog/pg_inherits.h"
#include "catalog/pg_language.h"
#include "catalog/pg_largeobject.h"
#include "catalog/pg_listener.h"
#include "catalog/pg_namespace.h"
#include "catalog/pg_opclass.h"
#include "catalog/pg_opfamily.h"
#include "catalog/pg_operator.h"
#include "catalog/pg_partition.h"
#include "catalog/pg_partition_rule.h"
#include "catalog/pg_pltemplate.h"
#include "catalog/pg_proc.h"
#include "catalog/pg_resqueue.h"
#include "catalog/pg_rewrite.h"
#include "catalog/pg_shdepend.h"
#include "catalog/pg_shdescription.h"
#include "catalog/pg_statistic.h"
#include "catalog/pg_tablespace.h"
#include "catalog/pg_trigger.h"
#include "catalog/pg_window.h"
#include "catalog/pg_tidycat.h"
#include "utils/fmgroids.h"
#include "utils/syscache.h"

/*
 * First, information about every datatype that is used in catalogs.
 * (This is maintained manually in catcoregen.pl, there are so many of these
 * and they change seldom.)
 */
static const CatCoreType CatCoreType_bool =
	{BOOLOID, F_BOOLEQ, F_BOOLLT, F_BOOLLE, F_BOOLGE, F_BOOLGT};
static const CatCoreType CatCoreType_bytea =
	{BYTEAOID, F_BYTEAEQ, F_BYTEALT, F_BYTEALE, F_BYTEAGE, F_BYTEAGT};
static const CatCoreType CatCoreType_char =
	{CHAROID, F_CHAREQ, F_CHARLT, F_CHARLE, F_CHARGE, F_CHARGT};
static const CatCoreType CatCoreType_NameData =
	{NAMEOID, F_NAMEEQ, F_NAMELT, F_NAMELE, F_NAMEGE, F_NAMEGT};
static const CatCoreType CatCoreType_int8 =
	{INT8OID, F_INT8EQ, F_INT8LT, F_INT8LE, F_INT8GE, F_INT8GT};
static const CatCoreType CatCoreType_int2 =
	{INT2OID, F_INT2EQ, F_INT2LT, F_INT2LE, F_INT2GE, F_INT2GT};
static const CatCoreType CatCoreType_int2vector =
	{INT2VECTOROID, InvalidOid, InvalidOid, InvalidOid, InvalidOid, InvalidOid};
static const CatCoreType CatCoreType_int4 =
	{INT4OID, F_INT4EQ, F_INT4LT, F_INT4LE, F_INT4GE, F_INT4GT};
static const CatCoreType CatCoreType_regproc =
	{REGPROCOID, F_OIDEQ, F_OIDLT, F_OIDLE, F_OIDGE, F_OIDGT};
static const CatCoreType CatCoreType_text =
	{TEXTOID, F_TEXTEQ, F_TEXT_LT, F_TEXT_LE, F_TEXT_GE, F_TEXT_GT};
static const CatCoreType CatCoreType_Oid =
	{OIDOID, F_OIDEQ, F_OIDLT, F_OIDLE, F_OIDGE, F_OIDGT};
static const CatCoreType CatCoreType_tid =
	{TIDOID, F_TIDEQ, F_TIDLT, F_TIDLE, F_TIDGE, F_TIDGT};
static const CatCoreType CatCoreType_TransactionId =
	{XIDOID, InvalidOid, InvalidOid, InvalidOid, InvalidOid, InvalidOid};
static const CatCoreType CatCoreType_oidvector =
	{OIDVECTOROID, F_OIDVECTOREQ, F_OIDVECTORLT, F_OIDVECTORLE, F_OIDVECTORGE, F_OIDVECTORGT};
static const CatCoreType CatCoreType_float4 =
	{FLOAT4OID, F_FLOAT4EQ, F_FLOAT4LT, F_FLOAT4LE, F_FLOAT4GE, F_FLOAT4GT};
static const CatCoreType CatCoreType_char_array =
	{1002, F_ARRAY_EQ, F_ARRAY_LT, F_ARRAY_LE, F_ARRAY_GE, F_ARRAY_GT};
static const CatCoreType CatCoreType_int2_array =
	{INT2ARRAYOID, F_ARRAY_EQ, F_ARRAY_LT, F_ARRAY_LE, F_ARRAY_GE, F_ARRAY_GT};
static const CatCoreType CatCoreType_int4_array =
	{INT4ARRAYOID, F_ARRAY_EQ, F_ARRAY_LT, F_ARRAY_LE, F_ARRAY_GE, F_ARRAY_GT};
static const CatCoreType CatCoreType_text_array =
	{TEXTARRAYOID, F_ARRAY_EQ, F_ARRAY_LT, F_ARRAY_LE, F_ARRAY_GE, F_ARRAY_GT};
static const CatCoreType CatCoreType_float4_array =
	{FLOAT4ARRAYOID, F_ARRAY_EQ, F_ARRAY_LT, F_ARRAY_LE, F_ARRAY_GE, F_ARRAY_GT};
static const CatCoreType CatCoreType_Oid_array =
	{1028, F_ARRAY_EQ, F_ARRAY_LT, F_ARRAY_LE, F_ARRAY_GE, F_ARRAY_GT};
static const CatCoreType CatCoreType_aclitem_array =
	{1034, F_ARRAY_EQ, F_ARRAY_LT, F_ARRAY_LE, F_ARRAY_GE, F_ARRAY_GT};
static const CatCoreType CatCoreType_time =
	{TIMEOID, F_TIME_EQ, F_TIME_LT, F_TIME_LE, F_TIME_GE, F_TIME_GT};
static const CatCoreType CatCoreType_timestamptz =
	{TIMESTAMPTZOID, F_TIMESTAMP_EQ, F_TIMESTAMP_LT, F_TIMESTAMP_LE, F_TIMESTAMP_GE, F_TIMESTAMP_GT};
static const CatCoreType CatCoreType_gpxlogloc =
	{XLOGLOCOID, F_GPXLOGLOCEQ, F_GPXLOGLOCLT, F_GPXLOGLOCLE, F_GPXLOGLOCGE, F_GPXLOGLOCGT};
static const CatCoreType CatCoreType_anyarray =
	{2277, F_ARRAY_EQ, F_ARRAY_LT, F_ARRAY_LE, F_ARRAY_GE, F_ARRAY_GT};

/* A pseudo-attr entry, for the "oid" system column */
const CatCoreAttr TableOidAttr = {
    "oid", ObjectIdAttributeNumber, &CatCoreType_Oid
};

/* Attributes for each relation (auto-generated from *.h files) */
static const CatCoreAttr gp_configurationAttributes[] = {
	{"content", 1, &CatCoreType_int2},
	{"definedprimary", 2, &CatCoreType_bool},
	{"dbid", 3, &CatCoreType_int2},
	{"isprimary", 4, &CatCoreType_bool},
	{"valid", 5, &CatCoreType_bool},
	{"hostname", 6, &CatCoreType_NameData},
	{"port", 7, &CatCoreType_int4},
	{"datadir", 8, &CatCoreType_text}
};
static const CatCoreAttr gp_configuration_historyAttributes[] = {
	{"time", 1, &CatCoreType_timestamptz},
	{"dbid", 2, &CatCoreType_int2},
	{"desc", 3, &CatCoreType_text}
};
static const CatCoreAttr gp_db_interfacesAttributes[] = {
	{"dbid", 1, &CatCoreType_int2},
	{"interfaceid", 2, &CatCoreType_int2},
	{"priority", 3, &CatCoreType_int2}
};
static const CatCoreAttr gp_distribution_policyAttributes[] = {
	{"localoid", 1, &CatCoreType_Oid},
	{"attrnums", 2, &CatCoreType_int2_array}
};
static const CatCoreAttr gp_fastsequenceAttributes[] = {
	{"objid", 1, &CatCoreType_Oid},
	{"objmod", 2, &CatCoreType_int8},
	{"last_sequence", 3, &CatCoreType_int8}
};
static const CatCoreAttr gp_fault_strategyAttributes[] = {
	{"fault_strategy", 1, &CatCoreType_char}
};
static const CatCoreAttr gp_global_sequenceAttributes[] = {
	{"sequence_num", 1, &CatCoreType_int8}
};
static const CatCoreAttr gp_idAttributes[] = {
	{"gpname", 1, &CatCoreType_NameData},
	{"numsegments", 2, &CatCoreType_int2},
	{"dbid", 3, &CatCoreType_int2},
	{"content", 4, &CatCoreType_int2}
};
static const CatCoreAttr gp_interfacesAttributes[] = {
	{"interfaceid", 1, &CatCoreType_int2},
	{"address", 2, &CatCoreType_NameData},
	{"status", 3, &CatCoreType_int2}
};
static const CatCoreAttr gp_persistent_database_nodeAttributes[] = {
	{"tablespace_oid", 1, &CatCoreType_Oid},
	{"database_oid", 2, &CatCoreType_Oid},
	{"persistent_state", 3, &CatCoreType_int2},
	{"create_mirror_data_loss_tracking_session_num", 4, &CatCoreType_int8},
	{"mirror_existence_state", 5, &CatCoreType_int2},
	{"reserved", 6, &CatCoreType_int4},
	{"parent_xid", 7, &CatCoreType_int4},
	{"persistent_serial_num", 8, &CatCoreType_int8},
	{"previous_free_tid", 9, &CatCoreType_tid}
};
static const CatCoreAttr gp_persistent_filespace_nodeAttributes[] = {
	{"filespace_oid", 1, &CatCoreType_Oid},
	{"db_id_1", 2, &CatCoreType_int2},
	{"location_1", 3, &CatCoreType_text},
	{"db_id_2", 4, &CatCoreType_int2},
	{"location_2", 5, &CatCoreType_text},
	{"persistent_state", 6, &CatCoreType_int2},
	{"create_mirror_data_loss_tracking_session_num", 7, &CatCoreType_int8},
	{"mirror_existence_state", 8, &CatCoreType_int2},
	{"reserved", 9, &CatCoreType_int4},
	{"parent_xid", 10, &CatCoreType_int4},
	{"persistent_serial_num", 11, &CatCoreType_int8},
	{"previous_free_tid", 12, &CatCoreType_tid}
};
static const CatCoreAttr gp_persistent_relation_nodeAttributes[] = {
	{"tablespace_oid", 1, &CatCoreType_Oid},
	{"database_oid", 2, &CatCoreType_Oid},
	{"relfilenode_oid", 3, &CatCoreType_Oid},
	{"segment_file_num", 4, &CatCoreType_int4},
	{"relation_storage_manager", 5, &CatCoreType_int2},
	{"persistent_state", 6, &CatCoreType_int2},
	{"create_mirror_data_loss_tracking_session_num", 7, &CatCoreType_int8},
	{"mirror_existence_state", 8, &CatCoreType_int2},
	{"mirror_data_synchronization_state", 9, &CatCoreType_int2},
	{"mirror_bufpool_marked_for_scan_incremental_resync", 10, &CatCoreType_bool},
	{"mirror_bufpool_resync_changed_page_count", 11, &CatCoreType_int8},
	{"mirror_bufpool_resync_ckpt_loc", 12, &CatCoreType_gpxlogloc},
	{"mirror_bufpool_resync_ckpt_block_num", 13, &CatCoreType_int4},
	{"mirror_append_only_loss_eof", 14, &CatCoreType_int8},
	{"mirror_append_only_new_eof", 15, &CatCoreType_int8},
	{"relation_bufpool_kind", 16, &CatCoreType_int4},
	{"parent_xid", 17, &CatCoreType_int4},
	{"persistent_serial_num", 18, &CatCoreType_int8},
	{"previous_free_tid", 19, &CatCoreType_tid}
};
static const CatCoreAttr gp_persistent_tablespace_nodeAttributes[] = {
	{"filespace_oid", 1, &CatCoreType_Oid},
	{"tablespace_oid", 2, &CatCoreType_Oid},
	{"persistent_state", 3, &CatCoreType_int2},
	{"create_mirror_data_loss_tracking_session_num", 4, &CatCoreType_int8},
	{"mirror_existence_state", 5, &CatCoreType_int2},
	{"reserved", 6, &CatCoreType_int4},
	{"parent_xid", 7, &CatCoreType_int4},
	{"persistent_serial_num", 8, &CatCoreType_int8},
	{"previous_free_tid", 9, &CatCoreType_tid}
};
static const CatCoreAttr gp_relation_nodeAttributes[] = {
	{"relfilenode_oid", 1, &CatCoreType_Oid},
	{"segment_file_num", 2, &CatCoreType_int4},
	{"create_mirror_data_loss_tracking_session_num", 3, &CatCoreType_int8},
	{"persistent_tid", 4, &CatCoreType_tid},
	{"persistent_serial_num", 5, &CatCoreType_int8}
};
static const CatCoreAttr gp_san_configurationAttributes[] = {
	{"mountid", 1, &CatCoreType_int2},
	{"active_host", 2, &CatCoreType_char},
	{"san_type", 3, &CatCoreType_char},
	{"primary_host", 4, &CatCoreType_text},
	{"primary_mountpoint", 5, &CatCoreType_text},
	{"primary_device", 6, &CatCoreType_text},
	{"mirror_host", 7, &CatCoreType_text},
	{"mirror_mountpoint", 8, &CatCoreType_text},
	{"mirror_device", 9, &CatCoreType_text}
};
static const CatCoreAttr gp_segment_configurationAttributes[] = {
	{"dbid", 1, &CatCoreType_int2},
	{"content", 2, &CatCoreType_int2},
	{"role", 3, &CatCoreType_char},
	{"preferred_role", 4, &CatCoreType_char},
	{"mode", 5, &CatCoreType_char},
	{"status", 6, &CatCoreType_char},
	{"port", 7, &CatCoreType_int4},
	{"hostname", 8, &CatCoreType_text},
	{"address", 9, &CatCoreType_text},
	{"replication_port", 10, &CatCoreType_int4},
	{"san_mounts", 11, &CatCoreType_int2vector}
};
static const CatCoreAttr gp_verification_historyAttributes[] = {
	{"vertoken", 1, &CatCoreType_NameData},
	{"vertype", 2, &CatCoreType_int2},
	{"vercontent", 3, &CatCoreType_int2},
	{"verstarttime", 4, &CatCoreType_timestamptz},
	{"verstate", 5, &CatCoreType_int2},
	{"verdone", 6, &CatCoreType_bool},
	{"verendtime", 7, &CatCoreType_timestamptz},
	{"vermismatch", 8, &CatCoreType_bool}
};
static const CatCoreAttr gp_version_at_initdbAttributes[] = {
	{"schemaversion", 1, &CatCoreType_int2},
	{"productversion", 2, &CatCoreType_text}
};
static const CatCoreAttr pg_aggregateAttributes[] = {
	{"aggfnoid", 1, &CatCoreType_regproc},
	{"aggtransfn", 2, &CatCoreType_regproc},
	{"agginvtransfn", 3, &CatCoreType_regproc},
	{"aggprelimfn", 4, &CatCoreType_regproc},
	{"agginvprelimfn", 5, &CatCoreType_regproc},
	{"aggfinalfn", 6, &CatCoreType_regproc},
	{"aggsortop", 7, &CatCoreType_Oid},
	{"aggtranstype", 8, &CatCoreType_Oid},
	{"agginitval", 9, &CatCoreType_text},
	{"aggordered", 10, &CatCoreType_bool}
};
static const CatCoreAttr pg_amAttributes[] = {
	{"amname", 1, &CatCoreType_NameData},
	{"amstrategies", 2, &CatCoreType_int2},
	{"amsupport", 3, &CatCoreType_int2},
	{"amorderstrategy", 4, &CatCoreType_int2},
	{"amdescorder", 5, &CatCoreType_int2},
	{"amcanunique", 6, &CatCoreType_bool},
	{"amcanmulticol", 7, &CatCoreType_bool},
	{"amoptionalkey", 8, &CatCoreType_bool},
	{"amindexnulls", 9, &CatCoreType_bool},
	{"amstorage", 10, &CatCoreType_bool},
	{"amclusterable", 11, &CatCoreType_bool},
	{"amcanshrink", 12, &CatCoreType_bool},
	{"aminsert", 13, &CatCoreType_regproc},
	{"ambeginscan", 14, &CatCoreType_regproc},
	{"amgettuple", 15, &CatCoreType_regproc},
	{"amgetmulti", 16, &CatCoreType_regproc},
	{"amrescan", 17, &CatCoreType_regproc},
	{"amendscan", 18, &CatCoreType_regproc},
	{"ammarkpos", 19, &CatCoreType_regproc},
	{"amrestrpos", 20, &CatCoreType_regproc},
	{"ambuild", 21, &CatCoreType_regproc},
	{"ambulkdelete", 22, &CatCoreType_regproc},
	{"amvacuumcleanup", 23, &CatCoreType_regproc},
	{"amcostestimate", 24, &CatCoreType_regproc},
	{"amoptions", 25, &CatCoreType_regproc}
};
static const CatCoreAttr pg_amopAttributes[] = {
	{"amopfamily", 1, &CatCoreType_Oid},
	{"amoplefttype", 2, &CatCoreType_Oid},
	{"amoprighttype", 3, &CatCoreType_Oid},
	{"amopstrategy", 4, &CatCoreType_int2},
	{"amopreqcheck", 5, &CatCoreType_bool},
	{"amopopr", 6, &CatCoreType_Oid},
	{"amopmethod", 7, &CatCoreType_Oid}
};
static const CatCoreAttr pg_amprocAttributes[] = {
	{"amprocfamily", 1, &CatCoreType_Oid},
	{"amproclefttype", 2, &CatCoreType_Oid},
	{"amprocrighttype", 3, &CatCoreType_Oid},
	{"amprocnum", 4, &CatCoreType_int2},
	{"amproc", 5, &CatCoreType_regproc}
};
static const CatCoreAttr pg_appendonlyAttributes[] = {
	{"relid", 1, &CatCoreType_Oid},
	{"blocksize", 2, &CatCoreType_int4},
	{"safefswritesize", 3, &CatCoreType_int4},
	{"compresslevel", 4, &CatCoreType_int2},
	{"majorversion", 5, &CatCoreType_int2},
	{"minorversion", 6, &CatCoreType_int2},
	{"checksum", 7, &CatCoreType_bool},
	{"compresstype", 8, &CatCoreType_text},
	{"columnstore", 9, &CatCoreType_bool},
	{"segrelid", 10, &CatCoreType_Oid},
	{"segidxid", 11, &CatCoreType_Oid},
	{"blkdirrelid", 12, &CatCoreType_Oid},
	{"blkdiridxid", 13, &CatCoreType_Oid},
	{"version", 14, &CatCoreType_int4},
	{"visimaprelid", 15, &CatCoreType_Oid},
	{"visimapidxid", 16, &CatCoreType_Oid}
};
static const CatCoreAttr pg_appendonly_alter_columnAttributes[] = {
	{"relid", 1, &CatCoreType_Oid},
	{"changenum", 2, &CatCoreType_int4},
	{"segfilenums", 3, &CatCoreType_int4_array},
	{"highwaterrownums", 4, &CatCoreType_bytea}
};
static const CatCoreAttr pg_attrdefAttributes[] = {
	{"adrelid", 1, &CatCoreType_Oid},
	{"adnum", 2, &CatCoreType_int2},
	{"adbin", 3, &CatCoreType_text},
	{"adsrc", 4, &CatCoreType_text}
};
static const CatCoreAttr pg_attributeAttributes[] = {
	{"attrelid", 1, &CatCoreType_Oid},
	{"attname", 2, &CatCoreType_NameData},
	{"atttypid", 3, &CatCoreType_Oid},
	{"attstattarget", 4, &CatCoreType_int4},
	{"attlen", 5, &CatCoreType_int2},
	{"attnum", 6, &CatCoreType_int2},
	{"attndims", 7, &CatCoreType_int4},
	{"attcacheoff", 8, &CatCoreType_int4},
	{"atttypmod", 9, &CatCoreType_int4},
	{"attbyval", 10, &CatCoreType_bool},
	{"attstorage", 11, &CatCoreType_char},
	{"attalign", 12, &CatCoreType_char},
	{"attnotnull", 13, &CatCoreType_bool},
	{"atthasdef", 14, &CatCoreType_bool},
	{"attisdropped", 15, &CatCoreType_bool},
	{"attislocal", 16, &CatCoreType_bool},
	{"attinhcount", 17, &CatCoreType_int4}
};
static const CatCoreAttr pg_attribute_encodingAttributes[] = {
	{"attrelid", 1, &CatCoreType_Oid},
	{"attnum", 2, &CatCoreType_int2},
	{"attoptions", 3, &CatCoreType_text_array}
};
static const CatCoreAttr pg_auth_membersAttributes[] = {
	{"roleid", 1, &CatCoreType_Oid},
	{"member", 2, &CatCoreType_Oid},
	{"grantor", 3, &CatCoreType_Oid},
	{"admin_option", 4, &CatCoreType_bool}
};
static const CatCoreAttr pg_auth_time_constraintAttributes[] = {
	{"authid", 1, &CatCoreType_Oid},
	{"start_day", 2, &CatCoreType_int2},
	{"start_time", 3, &CatCoreType_time},
	{"end_day", 4, &CatCoreType_int2},
	{"end_time", 5, &CatCoreType_time}
};
static const CatCoreAttr pg_authidAttributes[] = {
	{"rolname", 1, &CatCoreType_NameData},
	{"rolsuper", 2, &CatCoreType_bool},
	{"rolinherit", 3, &CatCoreType_bool},
	{"rolcreaterole", 4, &CatCoreType_bool},
	{"rolcreatedb", 5, &CatCoreType_bool},
	{"rolcatupdate", 6, &CatCoreType_bool},
	{"rolcanlogin", 7, &CatCoreType_bool},
	{"rolconnlimit", 8, &CatCoreType_int4},
	{"rolpassword", 9, &CatCoreType_text},
	{"rolvaliduntil", 10, &CatCoreType_timestamptz},
	{"rolconfig", 11, &CatCoreType_text_array},
	{"rolresqueue", 12, &CatCoreType_Oid},
	{"rolcreaterextgpfd", 13, &CatCoreType_bool},
	{"rolcreaterexthttp", 14, &CatCoreType_bool},
	{"rolcreatewextgpfd", 15, &CatCoreType_bool},
	{"rolcreaterexthdfs", 16, &CatCoreType_bool},
	{"rolcreatewexthdfs", 17, &CatCoreType_bool}
};
static const CatCoreAttr pg_autovacuumAttributes[] = {
	{"vacrelid", 1, &CatCoreType_Oid},
	{"enabled", 2, &CatCoreType_bool},
	{"vac_base_thresh", 3, &CatCoreType_int4},
	{"vac_scale_factor", 4, &CatCoreType_float4},
	{"anl_base_thresh", 5, &CatCoreType_int4},
	{"anl_scale_factor", 6, &CatCoreType_float4},
	{"vac_cost_delay", 7, &CatCoreType_int4},
	{"vac_cost_limit", 8, &CatCoreType_int4},
	{"freeze_min_age", 9, &CatCoreType_int4},
	{"freeze_max_age", 10, &CatCoreType_int4}
};
static const CatCoreAttr pg_castAttributes[] = {
	{"castsource", 1, &CatCoreType_Oid},
	{"casttarget", 2, &CatCoreType_Oid},
	{"castfunc", 3, &CatCoreType_Oid},
	{"castcontext", 4, &CatCoreType_char}
};
static const CatCoreAttr pg_classAttributes[] = {
	{"relname", 1, &CatCoreType_NameData},
	{"relnamespace", 2, &CatCoreType_Oid},
	{"reltype", 3, &CatCoreType_Oid},
	{"relowner", 4, &CatCoreType_Oid},
	{"relam", 5, &CatCoreType_Oid},
	{"relfilenode", 6, &CatCoreType_Oid},
	{"reltablespace", 7, &CatCoreType_Oid},
	{"relpages", 8, &CatCoreType_int4},
	{"reltuples", 9, &CatCoreType_float4},
	{"reltoastrelid", 10, &CatCoreType_Oid},
	{"reltoastidxid", 11, &CatCoreType_Oid},
	{"relaosegrelid", 12, &CatCoreType_Oid},
	{"relaosegidxid", 13, &CatCoreType_Oid},
	{"relhasindex", 14, &CatCoreType_bool},
	{"relisshared", 15, &CatCoreType_bool},
	{"relkind", 16, &CatCoreType_char},
	{"relstorage", 17, &CatCoreType_char},
	{"relnatts", 18, &CatCoreType_int2},
	{"relchecks", 19, &CatCoreType_int2},
	{"reltriggers", 20, &CatCoreType_int2},
	{"relukeys", 21, &CatCoreType_int2},
	{"relfkeys", 22, &CatCoreType_int2},
	{"relrefs", 23, &CatCoreType_int2},
	{"relhasoids", 24, &CatCoreType_bool},
	{"relhaspkey", 25, &CatCoreType_bool},
	{"relhasrules", 26, &CatCoreType_bool},
	{"relhassubclass", 27, &CatCoreType_bool},
	{"relfrozenxid", 28, &CatCoreType_TransactionId},
	{"relacl", 29, &CatCoreType_aclitem_array},
	{"reloptions", 30, &CatCoreType_text_array}
};
static const CatCoreAttr pg_compressionAttributes[] = {
	{"compname", 1, &CatCoreType_NameData},
	{"compconstructor", 2, &CatCoreType_regproc},
	{"compdestructor", 3, &CatCoreType_regproc},
	{"compcompressor", 4, &CatCoreType_regproc},
	{"compdecompressor", 5, &CatCoreType_regproc},
	{"compvalidator", 6, &CatCoreType_regproc},
	{"compowner", 7, &CatCoreType_Oid}
};
static const CatCoreAttr pg_constraintAttributes[] = {
	{"conname", 1, &CatCoreType_NameData},
	{"connamespace", 2, &CatCoreType_Oid},
	{"contype", 3, &CatCoreType_char},
	{"condeferrable", 4, &CatCoreType_bool},
	{"condeferred", 5, &CatCoreType_bool},
	{"conrelid", 6, &CatCoreType_Oid},
	{"contypid", 7, &CatCoreType_Oid},
	{"confrelid", 8, &CatCoreType_Oid},
	{"confupdtype", 9, &CatCoreType_char},
	{"confdeltype", 10, &CatCoreType_char},
	{"confmatchtype", 11, &CatCoreType_char},
	{"conkey", 12, &CatCoreType_int2_array},
	{"confkey", 13, &CatCoreType_int2_array},
	{"conbin", 14, &CatCoreType_text},
	{"consrc", 15, &CatCoreType_text}
};
static const CatCoreAttr pg_conversionAttributes[] = {
	{"conname", 1, &CatCoreType_NameData},
	{"connamespace", 2, &CatCoreType_Oid},
	{"conowner", 3, &CatCoreType_Oid},
	{"conforencoding", 4, &CatCoreType_int4},
	{"contoencoding", 5, &CatCoreType_int4},
	{"conproc", 6, &CatCoreType_regproc},
	{"condefault", 7, &CatCoreType_bool}
};
static const CatCoreAttr pg_databaseAttributes[] = {
	{"datname", 1, &CatCoreType_NameData},
	{"datdba", 2, &CatCoreType_Oid},
	{"encoding", 3, &CatCoreType_int4},
	{"datistemplate", 4, &CatCoreType_bool},
	{"datallowconn", 5, &CatCoreType_bool},
	{"datconnlimit", 6, &CatCoreType_int4},
	{"datlastsysoid", 7, &CatCoreType_Oid},
	{"datfrozenxid", 8, &CatCoreType_TransactionId},
	{"dattablespace", 9, &CatCoreType_Oid},
	{"datconfig", 10, &CatCoreType_text_array},
	{"datacl", 11, &CatCoreType_aclitem_array}
};
static const CatCoreAttr pg_dependAttributes[] = {
	{"classid", 1, &CatCoreType_Oid},
	{"objid", 2, &CatCoreType_Oid},
	{"objsubid", 3, &CatCoreType_int4},
	{"refclassid", 4, &CatCoreType_Oid},
	{"refobjid", 5, &CatCoreType_Oid},
	{"refobjsubid", 6, &CatCoreType_int4},
	{"deptype", 7, &CatCoreType_char}
};
static const CatCoreAttr pg_descriptionAttributes[] = {
	{"objoid", 1, &CatCoreType_Oid},
	{"classoid", 2, &CatCoreType_Oid},
	{"objsubid", 3, &CatCoreType_int4},
	{"description", 4, &CatCoreType_text}
};
static const CatCoreAttr pg_extprotocolAttributes[] = {
	{"ptcname", 1, &CatCoreType_NameData},
	{"ptcreadfn", 2, &CatCoreType_Oid},
	{"ptcwritefn", 3, &CatCoreType_Oid},
	{"ptcvalidatorfn", 4, &CatCoreType_Oid},
	{"ptcowner", 5, &CatCoreType_Oid},
	{"ptctrusted", 6, &CatCoreType_bool},
	{"ptcacl", 7, &CatCoreType_aclitem_array}
};
static const CatCoreAttr pg_exttableAttributes[] = {
	{"reloid", 1, &CatCoreType_Oid},
	{"location", 2, &CatCoreType_text_array},
	{"fmttype", 3, &CatCoreType_char},
	{"fmtopts", 4, &CatCoreType_text},
	{"command", 5, &CatCoreType_text},
	{"rejectlimit", 6, &CatCoreType_int4},
	{"rejectlimittype", 7, &CatCoreType_char},
	{"fmterrtbl", 8, &CatCoreType_Oid},
	{"encoding", 9, &CatCoreType_int4},
	{"writable", 10, &CatCoreType_bool}
};
static const CatCoreAttr pg_filespaceAttributes[] = {
	{"fsname", 1, &CatCoreType_NameData},
	{"fsowner", 2, &CatCoreType_Oid}
};
static const CatCoreAttr pg_filespace_entryAttributes[] = {
	{"fsefsoid", 1, &CatCoreType_Oid},
	{"fsedbid", 2, &CatCoreType_int2},
	{"fselocation", 3, &CatCoreType_text}
};
static const CatCoreAttr pg_indexAttributes[] = {
	{"indexrelid", 1, &CatCoreType_Oid},
	{"indrelid", 2, &CatCoreType_Oid},
	{"indnatts", 3, &CatCoreType_int2},
	{"indisunique", 4, &CatCoreType_bool},
	{"indisprimary", 5, &CatCoreType_bool},
	{"indisclustered", 6, &CatCoreType_bool},
	{"indisvalid", 7, &CatCoreType_bool},
	{"indkey", 8, &CatCoreType_int2vector},
	{"indclass", 9, &CatCoreType_oidvector},
	{"indoption", 10, &CatCoreType_int2vector},
	{"indexprs", 11, &CatCoreType_text},
	{"indpred", 12, &CatCoreType_text}
};
static const CatCoreAttr pg_inheritsAttributes[] = {
	{"inhrelid", 1, &CatCoreType_Oid},
	{"inhparent", 2, &CatCoreType_Oid},
	{"inhseqno", 3, &CatCoreType_int4}
};
static const CatCoreAttr pg_languageAttributes[] = {
	{"lanname", 1, &CatCoreType_NameData},
	{"lanispl", 2, &CatCoreType_bool},
	{"lanpltrusted", 3, &CatCoreType_bool},
	{"lanplcallfoid", 4, &CatCoreType_Oid},
	{"lanvalidator", 5, &CatCoreType_Oid},
	{"lanacl", 6, &CatCoreType_aclitem_array}
};
static const CatCoreAttr pg_largeobjectAttributes[] = {
	{"loid", 1, &CatCoreType_Oid},
	{"pageno", 2, &CatCoreType_int4},
	{"data", 3, &CatCoreType_bytea}
};
static const CatCoreAttr pg_listenerAttributes[] = {
	{"relname", 1, &CatCoreType_NameData},
	{"listenerpid", 2, &CatCoreType_int4},
	{"notification", 3, &CatCoreType_int4}
};
static const CatCoreAttr pg_namespaceAttributes[] = {
	{"nspname", 1, &CatCoreType_NameData},
	{"nspowner", 2, &CatCoreType_Oid},
	{"nspacl", 3, &CatCoreType_aclitem_array}
};
static const CatCoreAttr pg_opclassAttributes[] = {
	{"opcmethod", 1, &CatCoreType_Oid},
	{"opcname", 2, &CatCoreType_NameData},
	{"opcnamespace", 3, &CatCoreType_Oid},
	{"opcowner", 4, &CatCoreType_Oid},
	{"opcfamily", 5, &CatCoreType_Oid},
	{"opcintype", 6, &CatCoreType_Oid},
	{"opcdefault", 7, &CatCoreType_bool},
	{"opckeytype", 8, &CatCoreType_Oid}
};
static const CatCoreAttr pg_operatorAttributes[] = {
	{"oprname", 1, &CatCoreType_NameData},
	{"oprnamespace", 2, &CatCoreType_Oid},
	{"oprowner", 3, &CatCoreType_Oid},
	{"oprkind", 4, &CatCoreType_char},
	{"oprcanmerge", 5, &CatCoreType_bool},
	{"oprcanhash", 6, &CatCoreType_bool},
	{"oprleft", 7, &CatCoreType_Oid},
	{"oprright", 8, &CatCoreType_Oid},
	{"oprresult", 9, &CatCoreType_Oid},
	{"oprcom", 10, &CatCoreType_Oid},
	{"oprnegate", 11, &CatCoreType_Oid},
	{"oprcode", 12, &CatCoreType_regproc},
	{"oprrest", 13, &CatCoreType_regproc},
	{"oprjoin", 14, &CatCoreType_regproc}
};
static const CatCoreAttr pg_opfamilyAttributes[] = {
	{"opfmethod", 1, &CatCoreType_Oid},
	{"opfname", 2, &CatCoreType_NameData},
	{"opfnamespace", 3, &CatCoreType_Oid},
	{"opfowner", 4, &CatCoreType_Oid}
};
static const CatCoreAttr pg_partitionAttributes[] = {
	{"parrelid", 1, &CatCoreType_Oid},
	{"parkind", 2, &CatCoreType_char},
	{"parlevel", 3, &CatCoreType_int2},
	{"paristemplate", 4, &CatCoreType_bool},
	{"parnatts", 5, &CatCoreType_int2},
	{"paratts", 6, &CatCoreType_int2vector},
	{"parclass", 7, &CatCoreType_oidvector}
};
static const CatCoreAttr pg_partition_encodingAttributes[] = {
	{"parencoid", 1, &CatCoreType_Oid},
	{"parencattnum", 2, &CatCoreType_int2},
	{"parencattoptions", 3, &CatCoreType_text_array}
};
static const CatCoreAttr pg_partition_ruleAttributes[] = {
	{"paroid", 1, &CatCoreType_Oid},
	{"parchildrelid", 2, &CatCoreType_Oid},
	{"parparentrule", 3, &CatCoreType_Oid},
	{"parname", 4, &CatCoreType_NameData},
	{"parisdefault", 5, &CatCoreType_bool},
	{"parruleord", 6, &CatCoreType_int2},
	{"parrangestartincl", 7, &CatCoreType_bool},
	{"parrangeendincl", 8, &CatCoreType_bool},
	{"parrangestart", 9, &CatCoreType_text},
	{"parrangeend", 10, &CatCoreType_text},
	{"parrangeevery", 11, &CatCoreType_text},
	{"parlistvalues", 12, &CatCoreType_text},
	{"parreloptions", 13, &CatCoreType_text_array},
	{"partemplatespace", 14, &CatCoreType_Oid}
};
static const CatCoreAttr pg_pltemplateAttributes[] = {
	{"tmplname", 1, &CatCoreType_NameData},
	{"tmpltrusted", 2, &CatCoreType_bool},
	{"tmplhandler", 3, &CatCoreType_text},
	{"tmplvalidator", 4, &CatCoreType_text},
	{"tmpllibrary", 5, &CatCoreType_text},
	{"tmplacl", 6, &CatCoreType_aclitem_array}
};
static const CatCoreAttr pg_procAttributes[] = {
	{"proname", 1, &CatCoreType_NameData},
	{"pronamespace", 2, &CatCoreType_Oid},
	{"proowner", 3, &CatCoreType_Oid},
	{"prolang", 4, &CatCoreType_Oid},
	{"proisagg", 5, &CatCoreType_bool},
	{"prosecdef", 6, &CatCoreType_bool},
	{"proisstrict", 7, &CatCoreType_bool},
	{"proretset", 8, &CatCoreType_bool},
	{"provolatile", 9, &CatCoreType_char},
	{"pronargs", 10, &CatCoreType_int2},
	{"prorettype", 11, &CatCoreType_Oid},
	{"proiswin", 12, &CatCoreType_bool},
	{"proargtypes", 13, &CatCoreType_oidvector},
	{"proallargtypes", 14, &CatCoreType_Oid_array},
	{"proargmodes", 15, &CatCoreType_char_array},
	{"proargnames", 16, &CatCoreType_text_array},
	{"prosrc", 17, &CatCoreType_text},
	{"probin", 18, &CatCoreType_bytea},
	{"proacl", 19, &CatCoreType_aclitem_array},
	{"prodataaccess", 20, &CatCoreType_char}
};
static const CatCoreAttr pg_proc_callbackAttributes[] = {
	{"profnoid", 1, &CatCoreType_regproc},
	{"procallback", 2, &CatCoreType_regproc},
	{"promethod", 3, &CatCoreType_char}
};
static const CatCoreAttr pg_resourcetypeAttributes[] = {
	{"resname", 1, &CatCoreType_NameData},
	{"restypid", 2, &CatCoreType_int2},
	{"resrequired", 3, &CatCoreType_bool},
	{"reshasdefault", 4, &CatCoreType_bool},
	{"reshasdisable", 5, &CatCoreType_bool},
	{"resdefaultsetting", 6, &CatCoreType_text},
	{"resdisabledsetting", 7, &CatCoreType_text}
};
static const CatCoreAttr pg_resqueueAttributes[] = {
	{"rsqname", 1, &CatCoreType_NameData},
	{"rsqcountlimit", 2, &CatCoreType_float4},
	{"rsqcostlimit", 3, &CatCoreType_float4},
	{"rsqovercommit", 4, &CatCoreType_bool},
	{"rsqignorecostlimit", 5, &CatCoreType_float4}
};
static const CatCoreAttr pg_resqueuecapabilityAttributes[] = {
	{"resqueueid", 1, &CatCoreType_Oid},
	{"restypid", 2, &CatCoreType_int2},
	{"ressetting", 3, &CatCoreType_text}
};
static const CatCoreAttr pg_rewriteAttributes[] = {
	{"rulename", 1, &CatCoreType_NameData},
	{"ev_class", 2, &CatCoreType_Oid},
	{"ev_attr", 3, &CatCoreType_int2},
	{"ev_type", 4, &CatCoreType_char},
	{"is_instead", 5, &CatCoreType_bool},
	{"ev_qual", 6, &CatCoreType_text},
	{"ev_action", 7, &CatCoreType_text}
};
static const CatCoreAttr pg_shdependAttributes[] = {
	{"dbid", 1, &CatCoreType_Oid},
	{"classid", 2, &CatCoreType_Oid},
	{"objid", 3, &CatCoreType_Oid},
	{"refclassid", 4, &CatCoreType_Oid},
	{"refobjid", 5, &CatCoreType_Oid},
	{"deptype", 6, &CatCoreType_char}
};
static const CatCoreAttr pg_shdescriptionAttributes[] = {
	{"objoid", 1, &CatCoreType_Oid},
	{"classoid", 2, &CatCoreType_Oid},
	{"description", 3, &CatCoreType_text}
};
static const CatCoreAttr pg_stat_last_operationAttributes[] = {
	{"classid", 1, &CatCoreType_Oid},
	{"objid", 2, &CatCoreType_Oid},
	{"staactionname", 3, &CatCoreType_NameData},
	{"stasysid", 4, &CatCoreType_Oid},
	{"stausename", 5, &CatCoreType_NameData},
	{"stasubtype", 6, &CatCoreType_text},
	{"statime", 7, &CatCoreType_timestamptz}
};
static const CatCoreAttr pg_stat_last_shoperationAttributes[] = {
	{"classid", 1, &CatCoreType_Oid},
	{"objid", 2, &CatCoreType_Oid},
	{"staactionname", 3, &CatCoreType_NameData},
	{"stasysid", 4, &CatCoreType_Oid},
	{"stausename", 5, &CatCoreType_NameData},
	{"stasubtype", 6, &CatCoreType_text},
	{"statime", 7, &CatCoreType_timestamptz}
};
static const CatCoreAttr pg_statisticAttributes[] = {
	{"starelid", 1, &CatCoreType_Oid},
	{"staattnum", 2, &CatCoreType_int2},
	{"stanullfrac", 3, &CatCoreType_float4},
	{"stawidth", 4, &CatCoreType_int4},
	{"stadistinct", 5, &CatCoreType_float4},
	{"stakind1", 6, &CatCoreType_int2},
	{"stakind2", 7, &CatCoreType_int2},
	{"stakind3", 8, &CatCoreType_int2},
	{"stakind4", 9, &CatCoreType_int2},
	{"staop1", 10, &CatCoreType_Oid},
	{"staop2", 11, &CatCoreType_Oid},
	{"staop3", 12, &CatCoreType_Oid},
	{"staop4", 13, &CatCoreType_Oid},
	{"stanumbers1", 14, &CatCoreType_float4_array},
	{"stanumbers2", 15, &CatCoreType_float4_array},
	{"stanumbers3", 16, &CatCoreType_float4_array},
	{"stanumbers4", 17, &CatCoreType_float4_array},
	{"stavalues1", 18, &CatCoreType_anyarray},
	{"stavalues2", 19, &CatCoreType_anyarray},
	{"stavalues3", 20, &CatCoreType_anyarray},
	{"stavalues4", 21, &CatCoreType_anyarray}
};
static const CatCoreAttr pg_tablespaceAttributes[] = {
	{"spcname", 1, &CatCoreType_NameData},
	{"spcowner", 2, &CatCoreType_Oid},
	{"spclocation", 3, &CatCoreType_text},
	{"spcacl", 4, &CatCoreType_aclitem_array},
	{"spcprilocations", 5, &CatCoreType_text_array},
	{"spcmirlocations", 6, &CatCoreType_text_array},
	{"spcfsoid", 7, &CatCoreType_Oid}
};
static const CatCoreAttr pg_triggerAttributes[] = {
	{"tgrelid", 1, &CatCoreType_Oid},
	{"tgname", 2, &CatCoreType_NameData},
	{"tgfoid", 3, &CatCoreType_Oid},
	{"tgtype", 4, &CatCoreType_int2},
	{"tgenabled", 5, &CatCoreType_bool},
	{"tgisconstraint", 6, &CatCoreType_bool},
	{"tgconstrname", 7, &CatCoreType_NameData},
	{"tgconstrrelid", 8, &CatCoreType_Oid},
	{"tgdeferrable", 9, &CatCoreType_bool},
	{"tginitdeferred", 10, &CatCoreType_bool},
	{"tgnargs", 11, &CatCoreType_int2},
	{"tgattr", 12, &CatCoreType_int2vector},
	{"tgargs", 13, &CatCoreType_bytea}
};
static const CatCoreAttr pg_typeAttributes[] = {
	{"typname", 1, &CatCoreType_NameData},
	{"typnamespace", 2, &CatCoreType_Oid},
	{"typowner", 3, &CatCoreType_Oid},
	{"typlen", 4, &CatCoreType_int2},
	{"typbyval", 5, &CatCoreType_bool},
	{"typtype", 6, &CatCoreType_char},
	{"typisdefined", 7, &CatCoreType_bool},
	{"typdelim", 8, &CatCoreType_char},
	{"typrelid", 9, &CatCoreType_Oid},
	{"typelem", 10, &CatCoreType_Oid},
	{"typinput", 11, &CatCoreType_regproc},
	{"typoutput", 12, &CatCoreType_regproc},
	{"typreceive", 13, &CatCoreType_regproc},
	{"typsend", 14, &CatCoreType_regproc},
	{"typmodin", 15, &CatCoreType_regproc},
	{"typmodout", 16, &CatCoreType_regproc},
	{"typanalyze", 17, &CatCoreType_regproc},
	{"typalign", 18, &CatCoreType_char},
	{"typstorage", 19, &CatCoreType_char},
	{"typnotnull", 20, &CatCoreType_bool},
	{"typbasetype", 21, &CatCoreType_Oid},
	{"typtypmod", 22, &CatCoreType_int4},
	{"typndims", 23, &CatCoreType_int4},
	{"typdefaultbin", 24, &CatCoreType_text},
	{"typdefault", 25, &CatCoreType_text}
};
static const CatCoreAttr pg_type_encodingAttributes[] = {
	{"typid", 1, &CatCoreType_Oid},
	{"typoptions", 2, &CatCoreType_text_array}
};
static const CatCoreAttr pg_windowAttributes[] = {
	{"winfnoid", 1, &CatCoreType_regproc},
	{"winrequireorder", 2, &CatCoreType_bool},
	{"winallowframe", 3, &CatCoreType_bool},
	{"winpeercount", 4, &CatCoreType_bool},
	{"wincount", 5, &CatCoreType_bool},
	{"winfunc", 6, &CatCoreType_regproc},
	{"winprefunc", 7, &CatCoreType_regproc},
	{"winpretype", 8, &CatCoreType_Oid},
	{"winfinfunc", 9, &CatCoreType_regproc},
	{"winkind", 10, &CatCoreType_char},
	{"winframemakerfunc", 11, &CatCoreType_regproc}
};

/* Indexes for each relation (auto-generated from *.h files) */
static const CatCoreIndex gp_configurationIndexes[] = {
	/* gp_configuration_content_definedprimary_index */
	{6101, {
		Anum_gp_configuration_content /* gp_configuration int2_ops */,
		Anum_gp_configuration_definedprimary /* gp_configuration bool_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* gp_configuration_dbid_index */
	{6102, {
		Anum_gp_configuration_dbid /* gp_configuration int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex gp_configuration_historyIndexes[] = { };
static const CatCoreIndex gp_db_interfacesIndexes[] = {
	/* gp_db_interfaces_dbid_index */
	{6108, {
		Anum_gp_db_interfaces_dbid /* gp_db_interfaces int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex gp_distribution_policyIndexes[] = {
	/* gp_policy_localoid_index */
	{6103, {
		Anum_gp_policy_localoid /* gp_distribution_policy oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex gp_fastsequenceIndexes[] = {
	/* gp_fastsequence_objid_objmod_index */
	{6067, {
		Anum_gp_fastsequence_objid /* gp_fastsequence oid_ops */,
		Anum_gp_fastsequence_objmod /* gp_fastsequence  */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex gp_fault_strategyIndexes[] = { };
static const CatCoreIndex gp_global_sequenceIndexes[] = { };
static const CatCoreIndex gp_idIndexes[] = { };
static const CatCoreIndex gp_interfacesIndexes[] = {
	/* gp_interfaces_interface_index */
	{6109, {
		Anum_gp_interfaces_interfaceid /* gp_interfaces int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex gp_persistent_database_nodeIndexes[] = { };
static const CatCoreIndex gp_persistent_filespace_nodeIndexes[] = { };
static const CatCoreIndex gp_persistent_relation_nodeIndexes[] = { };
static const CatCoreIndex gp_persistent_tablespace_nodeIndexes[] = { };
static const CatCoreIndex gp_relation_nodeIndexes[] = {
	/* gp_relation_node_index */
	{5095, {
		Anum_gp_relation_node_relfilenode_oid /* gp_relation_node oid_ops */,
		Anum_gp_relation_node_segment_file_num /* gp_relation_node int4_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex gp_san_configurationIndexes[] = {
	/* gp_san_config_mountid_index */
	{6111, {
		Anum_gp_san_configuration_mountid /* gp_san_configuration int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex gp_segment_configurationIndexes[] = {
	/* gp_segment_config_content_preferred_role_index */
	{6106, {
		Anum_gp_segment_configuration_content /* gp_segment_configuration int2_ops */,
		Anum_gp_segment_configuration_preferred_role /* gp_segment_configuration char_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* gp_segment_config_dbid_index */
	{6107, {
		Anum_gp_segment_configuration_dbid /* gp_segment_configuration int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex gp_verification_historyIndexes[] = {
	/* gp_verification_history_vertoken_index */
	{6431, {
		Anum_gp_verification_history_vertoken /* gp_verification_history name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex gp_version_at_initdbIndexes[] = { };
static const CatCoreIndex pg_aggregateIndexes[] = {
	/* pg_aggregate_fnoid_index */
	{2650, {
		Anum_pg_aggregate_aggfnoid /* pg_aggregate oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_amIndexes[] = {
	/* pg_am_name_index */
	{2651, {
		Anum_pg_am_amname /* pg_am name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_am_oid_index */
	{2652, {
		ObjectIdAttributeNumber /* pg_am oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_amopIndexes[] = {
	/* pg_amop_fam_strat_index */
	{2653, {
		Anum_pg_amop_amopfamily /* pg_amop oid_ops */,
		Anum_pg_amop_amoplefttype /* pg_amop oid_ops */,
		Anum_pg_amop_amoprighttype /* pg_amop oid_ops */,
		Anum_pg_amop_amopstrategy /* pg_amop int2_ops */
	}, 4},
	/* pg_amop_opr_fam_index */
	{2654, {
		Anum_pg_amop_amopopr /* pg_amop oid_ops */,
		Anum_pg_amop_amopfamily /* pg_amop oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_amop_oid_index */
	{2756, {
		ObjectIdAttributeNumber /* pg_amop oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_amprocIndexes[] = {
	/* pg_amproc_fam_proc_index */
	{2655, {
		Anum_pg_amproc_amprocfamily /* pg_amproc oid_ops */,
		Anum_pg_amproc_amproclefttype /* pg_amproc oid_ops */,
		Anum_pg_amproc_amprocrighttype /* pg_amproc oid_ops */,
		Anum_pg_amproc_amprocnum /* pg_amproc int2_ops */
	}, 4},
	/* pg_amproc_oid_index */
	{2757, {
		ObjectIdAttributeNumber /* pg_amproc oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_appendonlyIndexes[] = {
	/* pg_appendonly_relid_index */
	{5007, {
		Anum_pg_appendonly_relid /* pg_appendonly oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_appendonly_alter_columnIndexes[] = {
	/* pg_appendonly_alter_column_relid_index */
	{5031, {
		Anum_pg_appendonly_alter_column_relid /* pg_appendonly_alter_column oid_ops */,
		Anum_pg_appendonly_alter_column_changenum /* pg_appendonly_alter_column int4_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_attrdefIndexes[] = {
	/* pg_attrdef_adrelid_adnum_index */
	{2656, {
		Anum_pg_attrdef_adrelid /* pg_attrdef oid_ops */,
		Anum_pg_attrdef_adnum /* pg_attrdef int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_attrdef_oid_index */
	{2657, {
		ObjectIdAttributeNumber /* pg_attrdef oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_attributeIndexes[] = {
	/* pg_attribute_relid_attnam_index */
	{2658, {
		Anum_pg_attribute_attrelid /* pg_attribute oid_ops */,
		Anum_pg_attribute_attname /* pg_attribute name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_attribute_relid_attnum_index */
	{2659, {
		Anum_pg_attribute_attrelid /* pg_attribute oid_ops */,
		Anum_pg_attribute_attnum /* pg_attribute int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_attribute_encodingIndexes[] = {
	/* pg_attribute_encoding_attrelid_index */
	{3236, {
		Anum_pg_attribute_encoding_attrelid /* pg_attribute_encoding oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_attribute_encoding_attrelid_attnum_index */
	{3237, {
		Anum_pg_attribute_encoding_attrelid /* pg_attribute_encoding oid_ops */,
		Anum_pg_attribute_encoding_attnum /* pg_attribute_encoding int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_auth_membersIndexes[] = {
	/* pg_auth_members_role_member_index */
	{2694, {
		Anum_pg_auth_members_roleid /* pg_auth_members oid_ops */,
		Anum_pg_auth_members_member /* pg_auth_members oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_auth_members_member_role_index */
	{2695, {
		Anum_pg_auth_members_member /* pg_auth_members oid_ops */,
		Anum_pg_auth_members_roleid /* pg_auth_members oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_auth_time_constraintIndexes[] = { };
static const CatCoreIndex pg_authidIndexes[] = {
	/* pg_authid_rolname_index */
	{2676, {
		Anum_pg_authid_rolname /* pg_authid name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_authid_oid_index */
	{2677, {
		ObjectIdAttributeNumber /* pg_authid oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_authid_rolresqueue_index */
	{6029, {
		Anum_pg_authid_rolresqueue /* pg_authid oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_autovacuumIndexes[] = {
	/* pg_autovacuum_vacrelid_index */
	{1250, {
		Anum_pg_autovacuum_vacrelid /* pg_autovacuum oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_castIndexes[] = {
	/* pg_cast_oid_index */
	{2660, {
		ObjectIdAttributeNumber /* pg_cast oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_cast_source_target_index */
	{2661, {
		Anum_pg_cast_castsource /* pg_cast oid_ops */,
		Anum_pg_cast_casttarget /* pg_cast oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_classIndexes[] = {
	/* pg_class_oid_index */
	{2662, {
		ObjectIdAttributeNumber /* pg_class oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_class_relname_nsp_index */
	{2663, {
		Anum_pg_class_relname /* pg_class name_ops */,
		Anum_pg_class_relnamespace /* pg_class oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_compressionIndexes[] = {
	/* pg_compression_oid_index */
	{3058, {
		ObjectIdAttributeNumber /* pg_compression oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_compression_compname_index */
	{3059, {
		Anum_pg_compression_compname /* pg_compression name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_constraintIndexes[] = {
	/* pg_constraint_conname_nsp_index */
	{2664, {
		Anum_pg_constraint_conname /* pg_constraint name_ops */,
		Anum_pg_constraint_connamespace /* pg_constraint oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_constraint_conrelid_index */
	{2665, {
		Anum_pg_constraint_conrelid /* pg_constraint oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_constraint_contypid_index */
	{2666, {
		Anum_pg_constraint_contypid /* pg_constraint oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_constraint_oid_index */
	{2667, {
		ObjectIdAttributeNumber /* pg_constraint oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_conversionIndexes[] = {
	/* pg_conversion_default_index */
	{2668, {
		Anum_pg_conversion_connamespace /* pg_conversion oid_ops */,
		Anum_pg_conversion_conforencoding /* pg_conversion int4_ops */,
		Anum_pg_conversion_contoencoding /* pg_conversion int4_ops */,
		ObjectIdAttributeNumber /* pg_conversion oid_ops */
	}, 4},
	/* pg_conversion_name_nsp_index */
	{2669, {
		Anum_pg_conversion_conname /* pg_conversion name_ops */,
		Anum_pg_conversion_connamespace /* pg_conversion oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_conversion_oid_index */
	{2670, {
		ObjectIdAttributeNumber /* pg_conversion oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_databaseIndexes[] = {
	/* pg_database_datname_index */
	{2671, {
		Anum_pg_database_datname /* pg_database name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_database_oid_index */
	{2672, {
		ObjectIdAttributeNumber /* pg_database oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_dependIndexes[] = {
	/* pg_depend_depender_index */
	{2673, {
		Anum_pg_depend_classid /* pg_depend oid_ops */,
		Anum_pg_depend_objid /* pg_depend oid_ops */,
		Anum_pg_depend_objsubid /* pg_depend int4_ops */,
		InvalidAttrNumber
	}, 3},
	/* pg_depend_reference_index */
	{2674, {
		Anum_pg_depend_refclassid /* pg_depend oid_ops */,
		Anum_pg_depend_refobjid /* pg_depend oid_ops */,
		Anum_pg_depend_refobjsubid /* pg_depend int4_ops */,
		InvalidAttrNumber
	}, 3}
};
static const CatCoreIndex pg_descriptionIndexes[] = {
	/* pg_description_o_c_o_index */
	{2675, {
		Anum_pg_description_objoid /* pg_description oid_ops */,
		Anum_pg_description_classoid /* pg_description oid_ops */,
		Anum_pg_description_objsubid /* pg_description int4_ops */,
		InvalidAttrNumber
	}, 3}
};
static const CatCoreIndex pg_extprotocolIndexes[] = {
	/* pg_extprotocol_oid_index */
	{7156, {
		ObjectIdAttributeNumber /* pg_extprotocol oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_extprotocol_ptcname_index */
	{7177, {
		Anum_pg_extprotocol_ptcname /* pg_extprotocol name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_exttableIndexes[] = {
	/* pg_exttable_reloid_index */
	{6041, {
		Anum_pg_exttable_reloid /* pg_exttable oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_filespaceIndexes[] = {
	/* pg_filespace_oid_index */
	{2858, {
		ObjectIdAttributeNumber /* pg_filespace oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_filespace_fsname_index */
	{2859, {
		Anum_pg_filespace_fsname /* pg_filespace name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_filespace_entryIndexes[] = {
	/* pg_filespace_entry_fs_index */
	{6090, {
		Anum_pg_filespace_entry_fsefsoid /* pg_filespace_entry oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_filespace_entry_fsdb_index */
	{6091, {
		Anum_pg_filespace_entry_fsefsoid /* pg_filespace_entry oid_ops */,
		Anum_pg_filespace_entry_fsedbid /* pg_filespace_entry int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_indexIndexes[] = {
	/* pg_index_indrelid_index */
	{2678, {
		Anum_pg_index_indrelid /* pg_index oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_index_indexrelid_index */
	{2679, {
		Anum_pg_index_indexrelid /* pg_index oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_inheritsIndexes[] = {
	/* pg_inherits_relid_seqno_index */
	{2680, {
		Anum_pg_inherits_inhrelid /* pg_inherits oid_ops */,
		Anum_pg_inherits_inhseqno /* pg_inherits int4_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_languageIndexes[] = {
	/* pg_language_lanname_index */
	{2681, {
		Anum_pg_language_lanname /* pg_language name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_language_oid_index */
	{2682, {
		ObjectIdAttributeNumber /* pg_language oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_largeobjectIndexes[] = {
	/* pg_largeobject_loid_pn_index */
	{2683, {
		Anum_pg_largeobject_loid /* pg_largeobject oid_ops */,
		Anum_pg_largeobject_pageno /* pg_largeobject int4_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_listenerIndexes[] = { };
static const CatCoreIndex pg_namespaceIndexes[] = {
	/* pg_namespace_nspname_index */
	{2684, {
		Anum_pg_namespace_nspname /* pg_namespace name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_namespace_oid_index */
	{2685, {
		ObjectIdAttributeNumber /* pg_namespace oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_opclassIndexes[] = {
	/* pg_opclass_am_name_nsp_index */
	{2686, {
		Anum_pg_opclass_opcmethod /* pg_opclass oid_ops */,
		Anum_pg_opclass_opcname /* pg_opclass name_ops */,
		Anum_pg_opclass_opcnamespace /* pg_opclass oid_ops */,
		InvalidAttrNumber
	}, 3},
	/* pg_opclass_oid_index */
	{2687, {
		ObjectIdAttributeNumber /* pg_opclass oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_operatorIndexes[] = {
	/* pg_operator_oid_index */
	{2688, {
		ObjectIdAttributeNumber /* pg_operator oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_operator_oprname_l_r_n_index */
	{2689, {
		Anum_pg_operator_oprname /* pg_operator name_ops */,
		Anum_pg_operator_oprleft /* pg_operator oid_ops */,
		Anum_pg_operator_oprright /* pg_operator oid_ops */,
		Anum_pg_operator_oprnamespace /* pg_operator oid_ops */
	}, 4}
};
static const CatCoreIndex pg_opfamilyIndexes[] = {
	/* pg_opfamily_am_name_nsp_index */
	{2754, {
		Anum_pg_opfamily_opfmethod /* pg_opfamily oid_ops */,
		Anum_pg_opfamily_opfname /* pg_opfamily name_ops */,
		Anum_pg_opfamily_opfnamespace /* pg_opfamily oid_ops */,
		InvalidAttrNumber
	}, 3},
	/* pg_opfamily_oid_index */
	{2755, {
		ObjectIdAttributeNumber /* pg_opfamily oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_partitionIndexes[] = {
	/* pg_partition_oid_index */
	{5012, {
		ObjectIdAttributeNumber /* pg_partition oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_partition_parrelid_index */
	{5013, {
		Anum_pg_partition_parrelid /* pg_partition oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_partition_parrelid_parlevel_istemplate_index */
	{5017, {
		Anum_pg_partition_parrelid /* pg_partition oid_ops */,
		Anum_pg_partition_parlevel /* pg_partition int2_ops */,
		Anum_pg_partition_paristemplate /* pg_partition bool_ops */,
		InvalidAttrNumber
	}, 3}
};
static const CatCoreIndex pg_partition_encodingIndexes[] = {
	/* pg_partition_encoding_parencoid_parencattnum_index */
	{9908, {
		Anum_pg_partition_encoding_parencoid /* pg_partition_encoding oid_ops */,
		Anum_pg_partition_encoding_parencattnum /* pg_partition_encoding int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_partition_encoding_parencoid_index */
	{9909, {
		Anum_pg_partition_encoding_parencoid /* pg_partition_encoding oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_partition_ruleIndexes[] = {
	/* pg_partition_rule_oid_index */
	{5014, {
		ObjectIdAttributeNumber /* pg_partition_rule oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_partition_rule_parchildrelid_index */
	{5016, {
		Anum_pg_partition_rule_parchildrelid /* pg_partition_rule oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_partition_rule_parchildrelid_parparentrule_parruleord_index */
	{5015, {
		Anum_pg_partition_rule_parchildrelid /* pg_partition_rule oid_ops */,
		Anum_pg_partition_rule_parparentrule /* pg_partition_rule oid_ops */,
		Anum_pg_partition_rule_parruleord /* pg_partition_rule int2_ops */,
		InvalidAttrNumber
	}, 3},
	/* pg_partition_rule_paroid_parentrule_ruleord_index */
	{5026, {
		Anum_pg_partition_rule_paroid /* pg_partition_rule oid_ops */,
		Anum_pg_partition_rule_parparentrule /* pg_partition_rule oid_ops */,
		Anum_pg_partition_rule_parruleord /* pg_partition_rule int2_ops */,
		InvalidAttrNumber
	}, 3}
};
static const CatCoreIndex pg_pltemplateIndexes[] = {
	/* pg_pltemplate_name_index */
	{1137, {
		Anum_pg_pltemplate_tmplname /* pg_pltemplate name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_procIndexes[] = {
	/* pg_proc_oid_index */
	{2690, {
		ObjectIdAttributeNumber /* pg_proc oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_proc_proname_args_nsp_index */
	{2691, {
		Anum_pg_proc_proname /* pg_proc name_ops */,
		Anum_pg_proc_proargtypes /* pg_proc oidvector_ops */,
		Anum_pg_proc_pronamespace /* pg_proc oid_ops */,
		InvalidAttrNumber
	}, 3}
};
static const CatCoreIndex pg_proc_callbackIndexes[] = {
	/* pg_proc_callback_profnoid_promethod_index */
	{3126, {
		Anum_pg_proc_callback_profnoid /* pg_proc_callback oid_ops */,
		Anum_pg_proc_callback_promethod /* pg_proc_callback char_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_resourcetypeIndexes[] = {
	/* pg_resourcetype_oid_index */
	{6061, {
		ObjectIdAttributeNumber /* pg_resourcetype oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_resourcetype_restypid_index */
	{6062, {
		Anum_pg_resourcetype_restypid /* pg_resourcetype int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_resourcetype_resname_index */
	{6063, {
		Anum_pg_resourcetype_resname /* pg_resourcetype name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_resqueueIndexes[] = {
	/* pg_resqueue_oid_index */
	{6027, {
		ObjectIdAttributeNumber /* pg_resqueue oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_resqueue_rsqname_index */
	{6028, {
		Anum_pg_resqueue_rsqname /* pg_resqueue name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_resqueuecapabilityIndexes[] = {
	/* pg_resqueuecapability_oid_index */
	{6064, {
		ObjectIdAttributeNumber /* pg_resqueuecapability oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_resqueuecapability_resqueueid_index */
	{6065, {
		Anum_pg_resqueuecapability_resqueueid /* pg_resqueuecapability oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_resqueuecapability_restypid_index */
	{6066, {
		Anum_pg_resqueuecapability_restypid /* pg_resqueuecapability int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_rewriteIndexes[] = {
	/* pg_rewrite_oid_index */
	{2692, {
		ObjectIdAttributeNumber /* pg_rewrite oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_rewrite_rel_rulename_index */
	{2693, {
		Anum_pg_rewrite_ev_class /* pg_rewrite oid_ops */,
		Anum_pg_rewrite_rulename /* pg_rewrite name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_shdependIndexes[] = {
	/* pg_shdepend_depender_index */
	{1232, {
		Anum_pg_shdepend_dbid /* pg_shdepend oid_ops */,
		Anum_pg_shdepend_classid /* pg_shdepend oid_ops */,
		Anum_pg_shdepend_objid /* pg_shdepend oid_ops */,
		InvalidAttrNumber
	}, 3},
	/* pg_shdepend_reference_index */
	{1233, {
		Anum_pg_shdepend_refclassid /* pg_shdepend oid_ops */,
		Anum_pg_shdepend_refobjid /* pg_shdepend oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_shdescriptionIndexes[] = {
	/* pg_shdescription_o_c_index */
	{2397, {
		Anum_pg_shdescription_objoid /* pg_shdescription oid_ops */,
		Anum_pg_shdescription_classoid /* pg_shdescription oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_stat_last_operationIndexes[] = {
	/* pg_statlastop_classid_objid_index */
	{6053, {
		Anum_pg_statlastop_classid /* pg_stat_last_operation oid_ops */,
		Anum_pg_statlastop_objid /* pg_stat_last_operation oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_statlastop_classid_objid_staactionname_index */
	{6054, {
		Anum_pg_statlastop_classid /* pg_stat_last_operation oid_ops */,
		Anum_pg_statlastop_objid /* pg_stat_last_operation oid_ops */,
		Anum_pg_statlastop_staactionname /* pg_stat_last_operation name_ops */,
		InvalidAttrNumber
	}, 3}
};
static const CatCoreIndex pg_stat_last_shoperationIndexes[] = {
	/* pg_statlastshop_classid_objid_index */
	{6057, {
		Anum_pg_statlastshop_classid /* pg_stat_last_shoperation oid_ops */,
		Anum_pg_statlastshop_objid /* pg_stat_last_shoperation oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_statlastshop_classid_objid_staactionname_index */
	{6058, {
		Anum_pg_statlastshop_classid /* pg_stat_last_shoperation oid_ops */,
		Anum_pg_statlastshop_objid /* pg_stat_last_shoperation oid_ops */,
		Anum_pg_statlastshop_staactionname /* pg_stat_last_shoperation name_ops */,
		InvalidAttrNumber
	}, 3}
};
static const CatCoreIndex pg_statisticIndexes[] = {
	/* pg_statistic_relid_att_index */
	{2696, {
		Anum_pg_statistic_starelid /* pg_statistic oid_ops */,
		Anum_pg_statistic_staattnum /* pg_statistic int2_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_tablespaceIndexes[] = {
	/* pg_tablespace_oid_index */
	{2697, {
		ObjectIdAttributeNumber /* pg_tablespace oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_tablespace_spcname_index */
	{2698, {
		Anum_pg_tablespace_spcname /* pg_tablespace name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_triggerIndexes[] = {
	/* pg_trigger_tgconstrname_index */
	{2699, {
		Anum_pg_trigger_tgconstrname /* pg_trigger name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_trigger_tgconstrrelid_index */
	{2700, {
		Anum_pg_trigger_tgconstrrelid /* pg_trigger oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_trigger_tgrelid_tgname_index */
	{2701, {
		Anum_pg_trigger_tgrelid /* pg_trigger oid_ops */,
		Anum_pg_trigger_tgname /* pg_trigger name_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2},
	/* pg_trigger_oid_index */
	{2702, {
		ObjectIdAttributeNumber /* pg_trigger oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_typeIndexes[] = {
	/* pg_type_oid_index */
	{2703, {
		ObjectIdAttributeNumber /* pg_type oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1},
	/* pg_type_typname_nsp_index */
	{2704, {
		Anum_pg_type_typname /* pg_type name_ops */,
		Anum_pg_type_typnamespace /* pg_type oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 2}
};
static const CatCoreIndex pg_type_encodingIndexes[] = {
	/* pg_type_encoding_typid_index */
	{3207, {
		Anum_pg_type_encoding_typid /* pg_type_encoding oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};
static const CatCoreIndex pg_windowIndexes[] = {
	/* pg_window_fnoid_index */
	{5005, {
		Anum_pg_window_winfnoid /* pg_window oid_ops */,
		InvalidAttrNumber,
		InvalidAttrNumber,
		InvalidAttrNumber
	}, 1}
};

/* List of catalog relations (auto-generated from *.h files) */
const int CatCoreRelationSize = 72;
const CatCoreRelation CatCoreRelations[72] = {
	{"gp_configuration", 5000, gp_configurationAttributes, lengthof(gp_configurationAttributes), gp_configurationIndexes, lengthof(gp_configurationIndexes), false},
	{"gp_configuration_history", 5006, gp_configuration_historyAttributes, lengthof(gp_configuration_historyAttributes), gp_configuration_historyIndexes, lengthof(gp_configuration_historyIndexes), false},
	{"gp_db_interfaces", 5029, gp_db_interfacesAttributes, lengthof(gp_db_interfacesAttributes), gp_db_interfacesIndexes, lengthof(gp_db_interfacesIndexes), false},
	{"gp_distribution_policy", 5002, gp_distribution_policyAttributes, lengthof(gp_distribution_policyAttributes), gp_distribution_policyIndexes, lengthof(gp_distribution_policyIndexes), false},
	{"gp_fastsequence", 5043, gp_fastsequenceAttributes, lengthof(gp_fastsequenceAttributes), gp_fastsequenceIndexes, lengthof(gp_fastsequenceIndexes), false},
	{"gp_fault_strategy", 5039, gp_fault_strategyAttributes, lengthof(gp_fault_strategyAttributes), gp_fault_strategyIndexes, lengthof(gp_fault_strategyIndexes), false},
	{"gp_global_sequence", 5096, gp_global_sequenceAttributes, lengthof(gp_global_sequenceAttributes), gp_global_sequenceIndexes, lengthof(gp_global_sequenceIndexes), false},
	{"gp_id", 5001, gp_idAttributes, lengthof(gp_idAttributes), gp_idIndexes, lengthof(gp_idIndexes), false},
	{"gp_interfaces", 5030, gp_interfacesAttributes, lengthof(gp_interfacesAttributes), gp_interfacesIndexes, lengthof(gp_interfacesIndexes), false},
	{"gp_persistent_database_node", 5091, gp_persistent_database_nodeAttributes, lengthof(gp_persistent_database_nodeAttributes), gp_persistent_database_nodeIndexes, lengthof(gp_persistent_database_nodeIndexes), false},
	{"gp_persistent_filespace_node", 5093, gp_persistent_filespace_nodeAttributes, lengthof(gp_persistent_filespace_nodeAttributes), gp_persistent_filespace_nodeIndexes, lengthof(gp_persistent_filespace_nodeIndexes), false},
	{"gp_persistent_relation_node", 5090, gp_persistent_relation_nodeAttributes, lengthof(gp_persistent_relation_nodeAttributes), gp_persistent_relation_nodeIndexes, lengthof(gp_persistent_relation_nodeIndexes), false},
	{"gp_persistent_tablespace_node", 5092, gp_persistent_tablespace_nodeAttributes, lengthof(gp_persistent_tablespace_nodeAttributes), gp_persistent_tablespace_nodeIndexes, lengthof(gp_persistent_tablespace_nodeIndexes), false},
	{"gp_relation_node", 5094, gp_relation_nodeAttributes, lengthof(gp_relation_nodeAttributes), gp_relation_nodeIndexes, lengthof(gp_relation_nodeIndexes), false},
	{"gp_san_configuration", 5035, gp_san_configurationAttributes, lengthof(gp_san_configurationAttributes), gp_san_configurationIndexes, lengthof(gp_san_configurationIndexes), false},
	{"gp_segment_configuration", 5036, gp_segment_configurationAttributes, lengthof(gp_segment_configurationAttributes), gp_segment_configurationIndexes, lengthof(gp_segment_configurationIndexes), false},
	{"gp_verification_history", 6429, gp_verification_historyAttributes, lengthof(gp_verification_historyAttributes), gp_verification_historyIndexes, lengthof(gp_verification_historyIndexes), false},
	{"gp_version_at_initdb", 5003, gp_version_at_initdbAttributes, lengthof(gp_version_at_initdbAttributes), gp_version_at_initdbIndexes, lengthof(gp_version_at_initdbIndexes), false},
	{"pg_aggregate", 2600, pg_aggregateAttributes, lengthof(pg_aggregateAttributes), pg_aggregateIndexes, lengthof(pg_aggregateIndexes), false},
	{"pg_am", 2601, pg_amAttributes, lengthof(pg_amAttributes), pg_amIndexes, lengthof(pg_amIndexes), true},
	{"pg_amop", 2602, pg_amopAttributes, lengthof(pg_amopAttributes), pg_amopIndexes, lengthof(pg_amopIndexes), true},
	{"pg_amproc", 2603, pg_amprocAttributes, lengthof(pg_amprocAttributes), pg_amprocIndexes, lengthof(pg_amprocIndexes), true},
	{"pg_appendonly", 6105, pg_appendonlyAttributes, lengthof(pg_appendonlyAttributes), pg_appendonlyIndexes, lengthof(pg_appendonlyIndexes), false},
	{"pg_appendonly_alter_column", 6110, pg_appendonly_alter_columnAttributes, lengthof(pg_appendonly_alter_columnAttributes), pg_appendonly_alter_columnIndexes, lengthof(pg_appendonly_alter_columnIndexes), false},
	{"pg_attrdef", 2604, pg_attrdefAttributes, lengthof(pg_attrdefAttributes), pg_attrdefIndexes, lengthof(pg_attrdefIndexes), true},
	{"pg_attribute", 1249, pg_attributeAttributes, lengthof(pg_attributeAttributes), pg_attributeIndexes, lengthof(pg_attributeIndexes), false},
	{"pg_attribute_encoding", 3231, pg_attribute_encodingAttributes, lengthof(pg_attribute_encodingAttributes), pg_attribute_encodingIndexes, lengthof(pg_attribute_encodingIndexes), false},
	{"pg_auth_members", 1261, pg_auth_membersAttributes, lengthof(pg_auth_membersAttributes), pg_auth_membersIndexes, lengthof(pg_auth_membersIndexes), false},
	{"pg_auth_time_constraint", 6070, pg_auth_time_constraintAttributes, lengthof(pg_auth_time_constraintAttributes), pg_auth_time_constraintIndexes, lengthof(pg_auth_time_constraintIndexes), false},
	{"pg_authid", 1260, pg_authidAttributes, lengthof(pg_authidAttributes), pg_authidIndexes, lengthof(pg_authidIndexes), true},
	{"pg_autovacuum", 1248, pg_autovacuumAttributes, lengthof(pg_autovacuumAttributes), pg_autovacuumIndexes, lengthof(pg_autovacuumIndexes), false},
	{"pg_cast", 2605, pg_castAttributes, lengthof(pg_castAttributes), pg_castIndexes, lengthof(pg_castIndexes), true},
	{"pg_class", 1259, pg_classAttributes, lengthof(pg_classAttributes), pg_classIndexes, lengthof(pg_classIndexes), true},
	{"pg_compression", 3056, pg_compressionAttributes, lengthof(pg_compressionAttributes), pg_compressionIndexes, lengthof(pg_compressionIndexes), true},
	{"pg_constraint", 2606, pg_constraintAttributes, lengthof(pg_constraintAttributes), pg_constraintIndexes, lengthof(pg_constraintIndexes), true},
	{"pg_conversion", 2607, pg_conversionAttributes, lengthof(pg_conversionAttributes), pg_conversionIndexes, lengthof(pg_conversionIndexes), true},
	{"pg_database", 1262, pg_databaseAttributes, lengthof(pg_databaseAttributes), pg_databaseIndexes, lengthof(pg_databaseIndexes), true},
	{"pg_depend", 2608, pg_dependAttributes, lengthof(pg_dependAttributes), pg_dependIndexes, lengthof(pg_dependIndexes), false},
	{"pg_description", 2609, pg_descriptionAttributes, lengthof(pg_descriptionAttributes), pg_descriptionIndexes, lengthof(pg_descriptionIndexes), false},
	{"pg_extprotocol", 7175, pg_extprotocolAttributes, lengthof(pg_extprotocolAttributes), pg_extprotocolIndexes, lengthof(pg_extprotocolIndexes), true},
	{"pg_exttable", 6040, pg_exttableAttributes, lengthof(pg_exttableAttributes), pg_exttableIndexes, lengthof(pg_exttableIndexes), false},
	{"pg_filespace", 5009, pg_filespaceAttributes, lengthof(pg_filespaceAttributes), pg_filespaceIndexes, lengthof(pg_filespaceIndexes), true},
	{"pg_filespace_entry", 5033, pg_filespace_entryAttributes, lengthof(pg_filespace_entryAttributes), pg_filespace_entryIndexes, lengthof(pg_filespace_entryIndexes), false},
	{"pg_index", 2610, pg_indexAttributes, lengthof(pg_indexAttributes), pg_indexIndexes, lengthof(pg_indexIndexes), false},
	{"pg_inherits", 2611, pg_inheritsAttributes, lengthof(pg_inheritsAttributes), pg_inheritsIndexes, lengthof(pg_inheritsIndexes), false},
	{"pg_language", 2612, pg_languageAttributes, lengthof(pg_languageAttributes), pg_languageIndexes, lengthof(pg_languageIndexes), true},
	{"pg_largeobject", 2613, pg_largeobjectAttributes, lengthof(pg_largeobjectAttributes), pg_largeobjectIndexes, lengthof(pg_largeobjectIndexes), false},
	{"pg_listener", 2614, pg_listenerAttributes, lengthof(pg_listenerAttributes), pg_listenerIndexes, lengthof(pg_listenerIndexes), false},
	{"pg_namespace", 2615, pg_namespaceAttributes, lengthof(pg_namespaceAttributes), pg_namespaceIndexes, lengthof(pg_namespaceIndexes), true},
	{"pg_opclass", 2616, pg_opclassAttributes, lengthof(pg_opclassAttributes), pg_opclassIndexes, lengthof(pg_opclassIndexes), true},
	{"pg_operator", 2617, pg_operatorAttributes, lengthof(pg_operatorAttributes), pg_operatorIndexes, lengthof(pg_operatorIndexes), true},
	{"pg_opfamily", 2753, pg_opfamilyAttributes, lengthof(pg_opfamilyAttributes), pg_opfamilyIndexes, lengthof(pg_opfamilyIndexes), true},
	{"pg_partition", 5010, pg_partitionAttributes, lengthof(pg_partitionAttributes), pg_partitionIndexes, lengthof(pg_partitionIndexes), true},
	{"pg_partition_encoding", 9903, pg_partition_encodingAttributes, lengthof(pg_partition_encodingAttributes), pg_partition_encodingIndexes, lengthof(pg_partition_encodingIndexes), false},
	{"pg_partition_rule", 5011, pg_partition_ruleAttributes, lengthof(pg_partition_ruleAttributes), pg_partition_ruleIndexes, lengthof(pg_partition_ruleIndexes), true},
	{"pg_pltemplate", 1136, pg_pltemplateAttributes, lengthof(pg_pltemplateAttributes), pg_pltemplateIndexes, lengthof(pg_pltemplateIndexes), false},
	{"pg_proc", 1255, pg_procAttributes, lengthof(pg_procAttributes), pg_procIndexes, lengthof(pg_procIndexes), true},
	{"pg_proc_callback", 3124, pg_proc_callbackAttributes, lengthof(pg_proc_callbackAttributes), pg_proc_callbackIndexes, lengthof(pg_proc_callbackIndexes), false},
	{"pg_resourcetype", 6059, pg_resourcetypeAttributes, lengthof(pg_resourcetypeAttributes), pg_resourcetypeIndexes, lengthof(pg_resourcetypeIndexes), true},
	{"pg_resqueue", 6026, pg_resqueueAttributes, lengthof(pg_resqueueAttributes), pg_resqueueIndexes, lengthof(pg_resqueueIndexes), true},
	{"pg_resqueuecapability", 6060, pg_resqueuecapabilityAttributes, lengthof(pg_resqueuecapabilityAttributes), pg_resqueuecapabilityIndexes, lengthof(pg_resqueuecapabilityIndexes), true},
	{"pg_rewrite", 2618, pg_rewriteAttributes, lengthof(pg_rewriteAttributes), pg_rewriteIndexes, lengthof(pg_rewriteIndexes), true},
	{"pg_shdepend", 1214, pg_shdependAttributes, lengthof(pg_shdependAttributes), pg_shdependIndexes, lengthof(pg_shdependIndexes), false},
	{"pg_shdescription", 2396, pg_shdescriptionAttributes, lengthof(pg_shdescriptionAttributes), pg_shdescriptionIndexes, lengthof(pg_shdescriptionIndexes), false},
	{"pg_stat_last_operation", 6052, pg_stat_last_operationAttributes, lengthof(pg_stat_last_operationAttributes), pg_stat_last_operationIndexes, lengthof(pg_stat_last_operationIndexes), false},
	{"pg_stat_last_shoperation", 6056, pg_stat_last_shoperationAttributes, lengthof(pg_stat_last_shoperationAttributes), pg_stat_last_shoperationIndexes, lengthof(pg_stat_last_shoperationIndexes), false},
	{"pg_statistic", 2619, pg_statisticAttributes, lengthof(pg_statisticAttributes), pg_statisticIndexes, lengthof(pg_statisticIndexes), false},
	{"pg_tablespace", 1213, pg_tablespaceAttributes, lengthof(pg_tablespaceAttributes), pg_tablespaceIndexes, lengthof(pg_tablespaceIndexes), true},
	{"pg_trigger", 2620, pg_triggerAttributes, lengthof(pg_triggerAttributes), pg_triggerIndexes, lengthof(pg_triggerIndexes), true},
	{"pg_type", 1247, pg_typeAttributes, lengthof(pg_typeAttributes), pg_typeIndexes, lengthof(pg_typeIndexes), true},
	{"pg_type_encoding", 3220, pg_type_encodingAttributes, lengthof(pg_type_encodingAttributes), pg_type_encodingIndexes, lengthof(pg_type_encodingIndexes), false},
	{"pg_window", 5004, pg_windowAttributes, lengthof(pg_windowAttributes), pg_windowIndexes, lengthof(pg_windowIndexes), false}
};
